export const PRODUCTS = [
  {
    id: 'croissant-mantequilla',
    name: 'Croissant de Mantequilla',
    category: 'Viennoiserie',
    price: 4.50,
    emoji: '🥐',
    gradient: 'linear-gradient(135deg, #F0E4C8 0%, #D4BC8A 100%)',
    featured: true,
    stock: 12,
    short: 'Elaborado con mantequilla francesa AOP, hojaldrado durante 72 horas.',
    long: 'Nuestro croissant es el resultado de tres días de paciencia. Mantequilla de calidad AOP francesa, harina de trigo de molino artesanal y tiempo—ese ingrediente que no puede apresurarse. Cada capa es una decisión consciente.',
    tags: ['clásico', 'mantequilla', 'hojaldre'],
  },
  {
    id: 'pain-au-chocolat',
    name: 'Pain au Chocolat',
    category: 'Viennoiserie',
    price: 5.00,
    emoji: '🍫',
    gradient: 'linear-gradient(135deg, #3D2B1F 0%, #7A4E32 60%, #C49A6C 100%)',
    featured: true,
    stock: 8,
    short: 'Dos barras de chocolate Valrhona 70% envueltas en masa hojaldrada.',
    long: 'El encuentro entre el hojaldre y el chocolate oscuro. Usamos chocolate Valrhona Guanaja 70%, cuyo amargor equilibrado dialoga con la dulzura suave de la masa. Un momento de indulgencia calculada.',
    tags: ['chocolate', 'valrhona'],
  },
  {
    id: 'pain-au-levain',
    name: 'Pain au Levain',
    category: 'Panes',
    price: 12.00,
    emoji: '🍞',
    gradient: 'linear-gradient(135deg, #C4A46B 0%, #8B6840 100%)',
    featured: true,
    stock: 6,
    short: 'Pan de masa madre con corteza caramelizada. Fermentación lenta de 18 horas.',
    long: 'Nuestro levain tiene cinco años de historia. Alimentado cada día, vive en el corazón de la panadería. Cada pan es una fermentación lenta, una corteza que suena a hueco, una miga que respira.',
    tags: ['masa madre', 'artesanal', '18h'],
  },
  {
    id: 'tarte-citron',
    name: 'Tarte au Citron',
    category: 'Tartas',
    price: 7.50,
    emoji: '🍋',
    gradient: 'linear-gradient(135deg, #F5E642 0%, #D4A017 60%, #F6F1E9 100%)',
    featured: false,
    stock: 4,
    short: 'Crema de limón Mayer sobre masa quebrada. Equilibrio entre acidez y dulzura.',
    long: 'Limones Mayer de huerta propia, ralladura fina, mantequilla y paciencia. La crema se cocina a bain-marie. La masa quebrada se hornea en ciego para conservar su fragilidad.',
    tags: ['tarta', 'limón', 'cítrico'],
  },
  {
    id: 'madeleine-vainilla',
    name: 'Madeleine de Vainilla',
    category: 'Pequeña pastelería',
    price: 3.00,
    emoji: '🫐',
    gradient: 'linear-gradient(135deg, #F6E8C4 0%, #C4A46B 100%)',
    featured: false,
    stock: 20,
    short: 'Vainilla Tahití, miel de acacia y mantequilla avellana. La madeleine de la memoria.',
    long: 'Hay sabores que son viajes. Nuestras madeleines se hacen con vainilla Tahití y un toque de miel de acacia. La mantequilla avellana da ese color dorado que reconocerás siempre.',
    tags: ['vainilla', 'miel', 'pequeño'],
  },
  {
    id: 'eclair-cafe',
    name: 'Éclair de Café',
    category: 'Pastelería',
    price: 6.50,
    emoji: '☕',
    gradient: 'linear-gradient(135deg, #3A2518 0%, #8B5E3C 60%, #C4A46B 100%)',
    featured: true,
    stock: 6,
    short: 'Pasta choux rellena de crema de café etíope. Glaseado de café negro.',
    long: 'Café etíope de tueste lento, crema pastelera infusionada en frío durante doce horas y pasta choux perfectamente esférica. El glaseado es oscuro, intenso—un contrapunto exacto a la dulzura de la crema.',
    tags: ['café', 'éclair', 'etíope'],
  },
  {
    id: 'brioche-azafran',
    name: 'Brioche de Azafrán',
    category: 'Panes',
    price: 8.50,
    emoji: '🌼',
    gradient: 'linear-gradient(135deg, #F5C842 0%, #E8A020 100%)',
    featured: false,
    stock: 3,
    short: 'Brioche enriquecida con azafrán de La Mancha. Esponjosa y aromática.',
    long: 'El azafrán de La Mancha tiñe de dorado profundo la miga y perfuma el horneado. Esta brioche es una celebración del color y el aroma.',
    tags: ['brioche', 'azafrán', 'especial'],
  },
  {
    id: 'financier-almendras',
    name: 'Financier de Almendras',
    category: 'Pequeña pastelería',
    price: 3.50,
    emoji: '🟫',
    gradient: 'linear-gradient(135deg, #C49A6C 0%, #8B6840 100%)',
    featured: false,
    stock: 15,
    short: 'Bizcocho de almendra tostada y mantequilla avellana. Crujiente por fuera, húmedo por dentro.',
    long: 'Las almendras se tuestan hasta que liberan sus aceites, la mantequilla se avellana con cuidado, y el resultado es un pequeño lingote dorado con una textura que no puedes olvidar.',
    tags: ['almendra', 'pequeño', 'dorado'],
  },
]

export const CATEGORIES = ['Viennoiserie', 'Panes', 'Tartas', 'Pastelería', 'Pequeña pastelería']
